### ISSUE TITLE
Event triggering and timing

### ISSUE THREAD

**Issue by dburongarcia** [sam0737/ShowCueWeb#1]
Hi, I was checking your code and I was wondering what was your event triggering strategy. Could a JSON list of every cue to create eventListeners dynamically work well or it is better to not use listeners at all and just check the list sequentially? What about the timing? Using Javascript timing events directly wouldn't be a bit 'too risky' without some kind of feedback from Date to check that everything is synchronized? Congratulations for your good job with your system.

**Comment by sam0737** [comment]
Sorry I wasn't actively maintaining this hence missed your message. (Basically I am only using this once a year LOL.)

Take a look at `stagecue-renderer.js`, the `go()` function returns a `promise` which is resolved at specific triggers (to be mentioned below). Once it's resolved, it kicks the `stagecue-cueengine.js` Line 459 to move on.

Here are few examples when the promise is resolved
* When the media ends (onended event)
* Upon a specific delay (setTimeout), if so configured in the cue
* Upon CSS animation ends (animationend event), if so configured in the cue

Today computer is fast enough that timing is not a practical issue. I didn't pay special attention to that.
